[versions]
projectApplicationId = "ir.composenews"
projectVersionName = "1.0"
projectMinSdkVersion = "23"
projectTargetSdkVersion = "34"
projectCompileSdkVersion = "34"
projectVersionCode = "1"

kotlin = "1.9.10"
kotlinter = "3.16.0"
ksp = "1.9.10-1.0.13"
kotlinxImmutableCollection = "0.3.5"
androidGradlePlugin = "8.1.1"

ktx = "1.12.0"

composeBOM = "2023.09.01"
composeActivity = "1.7.2"
composeCoil = "2.2.2"
composeCompiler = "1.5.3"
composeMaterial3 = "1.1.2"
detekt = "1.23.0"
hilt = "2.48"
androidHiltCompiler = "1.0.0"
hiltNavigationCompose = "1.0.0"
hiltWork = "1.0.0"
javaxInject = "1"

coroutinesCore = "1.7.3"

lifeCycle = "2.6.2"
lifeCycleViewModelKtx = "2.6.2"
lifeCycleRuntimeCompose = "2.6.2"

navigationCompose = "2.7.2"

retrofit = "2.9.0"
loggingInterceptor = "4.11.0"
chucker = "3.5.2"
kotlinx-serialization = "1.6.0"
kotlinx-serialization-converter = "1.0.0"

room = "2.6.0-rc01"

junit = "4.13.2"
junitExt = "1.1.5"
coroutinesTest = "1.7.3"
mockitoKotlin = "4.1.0"
mockk = "1.13.5"
runner = "1.5.2"

startupRuntime = "1.1.1"

workRuntimeKtx = "2.8.1"

windowsSizeClass = "1.1.2"
adaptive = "0.26.2-beta"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBOM" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "composeCompiler" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "composeCoil" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidHiltCompiler" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutinesCore" }

lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifeCycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifeCycleViewModelKtx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifeCycleRuntimeCompose" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mokito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }

work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutableCollection" }

window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "windowsSizeClass" }
accomponist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "adaptive" }

# Dependencies of the included build-logic
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
ktlint-kotlinter = { group = "org.jmailen.gradle", name = "kotlinter-gradle", version.ref = "kotlinter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotliner = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-preview",
    "compose-ui-tooling",
    "compose-ui-test-manifest",
    "compose-material3",
]
room = [
    "room-ktx",
    "room-runtime",
]